In [1]:
from keras.utils import to_categorical
import numpy as np
x = np.reshape(np.r_[0:128*5],newshape=(128,-1))
x = np.expand_dims(x, axis= -1)
y = []
for idx in range(3):
   y.append(to_categorical(np.random.randint(0,size=128,high=10)))
# y = np.arange(10)
# y= [y,y,y]

print(len(x))
print([len(each) for each in y] + [len(x)])

C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


128
[128, 128, 128, 128]


In [2]:
target = np.argmax(y[0],axis=-1)
labels = np.unique(target)
labels[np.bincount(target)<10]

array([3, 5, 9], dtype=int64)

In [3]:
try:
    del BalancedAudioDataGenerator
except:
    ;
from AdvAudioDataGenerator import BalancedAudioDataGenerator
datagen = BalancedAudioDataGenerator()

In [4]:
y

[array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 0.]], dtype=float32),
 array([[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]

In [5]:
batchx,batchy = next(datagen.flow(x=x,y=y,target_label=1,batch_size=100))

Chunk size selected as 10
Total batches seen 1
Batch Index 1
Current Index [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]


E:\SleepWell\ASSC\codes\AdvAudioDataGenerator.py:40: UserWarning: Number of samples for label [4 5] is smaller than chunk size 10
  <self.chunk_size]),self.chunk_size))


In [6]:
type(y) == list

True

In [7]:
batchx[:,:,0].shape

(97, 5)

In [8]:
if type(batchy) == list:
    for each in batchy:
        print(each.shape)
else:
    np.bincount(np.argmax(batchy,axis=-1))

(97, 10)
(97, 10)
(97, 10)
