In [78]:
from keras.utils import to_categorical
import numpy as np
x = np.reshape(np.r_[0:128*5],newshape=(128,-1))
x = np.expand_dims(x, axis= -1)
y = []
for idx in range(3):
   y.append(to_categorical(np.random.randint(0,size=128,high=10)))
# y = np.arange(10)
# y= [y,y,y]

print(len(x))
print([len(each) for each in y] + [len(x)])
y[0] = np.argmax(y[0],axis=-1)

128
[128, 128, 128, 128]


In [81]:
try:
    del BalancedAudioDataGenerator
except:
    ;
from AdvAudioDataGenerator import BalancedAudioDataGenerator
datagen = BalancedAudioDataGenerator().flow(x,y.copy(),target_label=1,batch_size=32)

Chunk size selected as 3


In [82]:
# y[0] = np.argmax(y[0],axis=-1)
y

[array([3, 7, 7, 3, 0, 5, 5, 8, 4, 0, 7, 1, 5, 7, 3, 0, 9, 4, 8, 7, 5, 9,
        1, 1, 3, 4, 0, 0, 7, 8, 1, 7, 9, 2, 5, 4, 4, 4, 2, 6, 2, 0, 5, 8,
        6, 7, 4, 8, 0, 6, 2, 7, 9, 7, 8, 9, 3, 8, 9, 7, 2, 5, 1, 4, 6, 2,
        0, 2, 9, 3, 3, 9, 3, 7, 7, 7, 5, 4, 7, 7, 1, 6, 9, 4, 0, 2, 2, 5,
        6, 4, 4, 9, 5, 1, 0, 4, 5, 2, 0, 0, 9, 5, 2, 2, 7, 6, 7, 9, 1, 9,
        9, 3, 5, 7, 7, 6, 9, 0, 6, 9, 5, 0, 0, 1, 9, 2, 3, 6], dtype=int64),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]

In [85]:
batchx,batchy = next(datagen)

Total batches seen 3
Batch Index 3
Current Index [9, 9, 9, 9, 9, 3, 9, 9, 9, 9]


In [86]:
batchx[:,:,0].shape

(30, 5)

In [87]:
if type(batchy) == list:
    for each in batchy:
        print(each)
else:
    np.bincount(np.argmax(batchy,axis=-1))

[7 4 4 2 0 0 8 1 1 9 2 9 2 6 3 6 2 4 5 0 7 0 7 1 0 9 7 0 1 0]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 