In [1]:
from keras.utils import to_categorical
import numpy as np
x = np.reshape(np.r_[0:128*5],newshape=(128,-1))
x = np.expand_dims(x, axis= -1)
y = []
for idx in range(3):
   y.append(to_categorical(np.random.randint(0,size=128,high=10)))
# y = np.arange(10)
# y= [y,y,y]

print(len(x))
print([len(each) for each in y] + [len(x)])
y[0] = np.argmax(y[0],axis=-1)

C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


128
[128, 128, 128, 128]


In [119]:
try:
    del BalancedAudioDataGenerator
except:
    ;
from AudioDataGenerator import BalancedAudioDataGenerator
datagen = BalancedAudioDataGenerator(samplewise_center=True,roll_range=.5)
print(datagen.random_transform(x[0]))
datagen = datagen.flow(x,y,target_label=1,batch_size=32)

[[0]
 [1]
 [2]
 [3]
 [4]]
Chunk size selected as 3


In [120]:
# y[0] = np.argmax(y[0],axis=-1)
y

[array([8, 7, 3, 0, 6, 2, 1, 2, 0, 3, 2, 1, 2, 1, 3, 8, 4, 2, 5, 2, 8, 1,
        8, 1, 0, 1, 6, 6, 8, 1, 3, 1, 1, 2, 1, 6, 3, 6, 9, 3, 4, 1, 2, 1,
        1, 2, 2, 6, 7, 2, 8, 7, 8, 6, 2, 2, 8, 5, 4, 0, 0, 9, 7, 8, 8, 4,
        7, 3, 2, 9, 4, 5, 8, 3, 8, 9, 6, 4, 1, 2, 1, 4, 3, 1, 9, 9, 1, 0,
        3, 6, 1, 8, 5, 8, 6, 3, 7, 5, 5, 1, 3, 8, 5, 6, 4, 6, 1, 6, 7, 8,
        7, 0, 1, 0, 5, 7, 0, 8, 6, 2, 4, 9, 9, 4, 4, 4, 7, 4], dtype=int64),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)]

In [121]:
batchx,batchy = next(datagen)
batchx[:,:,0]

Total batches seen 1
Batch Index 1
Current Index [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


array([[-2., -1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2., -2.],
       [-1.,  0.,  1.,  2., -2.],
       [ 0.,  1.,  2., -2., -1.],
       [-2., -1.,  0.,  1.,  2.],
       [ 1.,  2., -2., -1.,  0.],
       [ 0.,  1.,  2., -2., -1.],
       [-2., -1.,  0.,  1.,  2.],
       [ 1.,  2., -2., -1.,  0.],
       [-1.,  0.,  1.,  2., -2.],
       [-1.,  0.,  1.,  2., -2.],
       [ 0.,  1.,  2., -2., -1.],
       [-1.,  0.,  1.,  2., -2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [ 2., -2., -1.,  0.,  1.],
       [-2., -1.,  0.,  1.,  2.],
       [ 2., -2., -1.,  0.,  1.],
       [ 0.,  1.,  2., -2., -1.],
       [-1.,  0.,  1.,  2., -2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [ 2., -2., -1.,  0.,  1.],
       [ 2., -2., -1.,  0.,  1.],
       [ 1.,  2., -2., -1.,  0.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [ 2., -

In [5]:
if type(batchy) == list:
    for each in batchy:
        print(each.shape)
else:
    np.bincount(np.argmax(batchy,axis=-1))

(30,)
(30, 10)
(30, 10)
