In [1]:
from keras.utils import to_categorical
import numpy as np
x = np.random.randn(128,20)
x = np.expand_dims(x, axis= -1)
y = []
for idx in range(3):
   y.append(to_categorical(np.random.randint(0,size=128,high=3)))
# y = np.arange(10)
# y= [y,y,y]

print(len(x))
print([len(each) for each in y])

C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


128
[128, 128, 128]


In [2]:
try:
    del AudioDataGenerator
except:
    ;
from AdvAudioDataGenerator import AudioDataGenerator
datagen = AudioDataGenerator()

In [3]:
for idx,each in enumerate(datagen.flow(x=x,y=y[0])):
    print(each[1])
    if idx>5:
        break

Chunk_size selected as 10
Total batches seen1
Batch Index 0
Current Index [10, 10, 10]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
Total batches seen2
Batch Index 1
Current Index [20, 20, 20]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
Total batches seen3
Batch Index 2
Current Index [30, 30, 30]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0

In [4]:
next(datagen.flow(x=x,y=y[0]))

Chunk_size selected as 10
Total batches seen1
Batch Index 0
Current Index [10, 10, 10]


(array([[[ 1.59822442e-02],
         [ 6.80057347e-01],
         [ 1.26361036e+00],
         [-1.68983698e-01],
         [-1.41695037e-01],
         [-1.34149686e-01],
         [-4.14006971e-02],
         [ 1.15601920e-01],
         [-1.23282552e+00],
         [ 4.56922114e-01],
         [ 7.63968945e-01],
         [-8.44333231e-01],
         [-3.78536999e-01],
         [-7.64623225e-01],
         [ 1.26730859e+00],
         [ 4.11192119e-01],
         [ 3.70408446e-01],
         [ 9.55041707e-01],
         [ 5.00489295e-01],
         [ 5.19957840e-01]],
 
        [[ 9.69602540e-03],
         [ 1.05813706e+00],
         [-1.67570066e+00],
         [-1.21315196e-01],
         [ 1.14450121e+00],
         [-1.07980967e+00],
         [ 4.24592793e-01],
         [-4.18568701e-01],
         [-7.48930573e-01],
         [-1.35654366e+00],
         [ 3.69888395e-01],
         [ 2.19090199e+00],
         [ 1.93037069e+00],
         [-7.87203968e-01],
         [ 6.63450420e-01],
         [-1.5563