In [1]:
import pandas as pd
def patientSplitter(randomIDfile,df2,split_portion):
    import pandas as pd

    df1 = pd.read_csv(randomIDfile,header=None)
    split_portion_numer=int(split_portion*61)

    train_pat_list = [int(each) for each in df1.iloc[:split_portion_numer].values]
    test_pat_list = [int(each) for each in df1.iloc[split_portion_numer:].values]
    print(test_pat_list)
    df3 = []
    df4 = []
    for pat_ID in train_pat_list:
        df3.append(df2[df2.patID == pat_ID].values)
        print(pat_ID)
    for pat_ID in test_pat_list:
        df4.append(df2[df2.patID == pat_ID].values)
        print(pat_ID)
    del df2
    df3 = pd.np.vstack(df3)
    df4 = pd.np.vstack(df4)
    X_train = df3[:, :3000]
    X_test= df4[:, :3000]
    Y_train= df3[:,3000]
    Y_test= df4[:,3000]
    pat_train=df3[:, 3002:3003]
    pat_test= df4[:, 3002:3003]

    del pd
    return X_train,X_test,Y_train,Y_test,pat_train,pat_test

df2 = pd.read_csv('E:/SleepWell/ASSC-master/data/purifiedallDataChannel2.csv', header=None)
df2.rename({3000: 'hyp', 3001: 'epoch', 3002: 'patID'}, axis="columns", inplace=True)

trainX, valX, trainY, valY, pat_train, pat_val = patientSplitter('randomizedIDs.csv', df2, 0.7)
print("Dataframe has been loaded")

[14, 30, 11, 15, 29, 8, 48, 24, 40, 54, 16, 37, 10, 39, 7, 18, 42, 57, 31]
35
21
22
43
9
56
34
58
26
6
3
55
33
2
27
13
46
45
38
47
17
5
25
32
1
52
50
12
41
51
4
19
0
23
53
49
36
20
44
60
59
28
14
30
11
15
29
8
48
24
40
54
16
37
10
39
7
18
42
57
31
Dataframe has been loaded


In [2]:
from AudioDataGenerator import *

C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [ ]:
#sample_wise_centre
#sample_wise_std




In [66]:
import numpy as np
from sklearn.metrics import accuracy_score
patAcc=[]
valYp = np.expand_dims(valY, axis=1)
for pat in np.unique(pat_val).astype(int):
    mask = pat_val==pat
    patAcc.append(accuracy_score(valYp[mask], valYp[mask]))
    #print(acc)
print(patAcc)    
    

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [77]:
from keras.utils import to_categorical, plot_model
valYp = to_categorical(valY-1, 7)
valYp = np.argmax(valYp, axis=-1)
valYp = np.expand_dims(valYp, axis=1)

In [115]:
#predY = model.predict(self.valX, verbose=0)
            # predY = np.argmax(predY, axis=-1)
patAcc = []
for pat in np.unique(pat_val).astype(int):
    mask = pat_val == pat
    patAcc.append(accuracy_score(valYp[mask], valYp[mask]))
print(patAcc)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [116]:
print(pat_val.shape)
print(valY.shape)
print(valYp.shape)

(43144, 1)
(43144,)
(43144, 1)


In [102]:
def compute_weight(Y, classes):
    num_samples = len(Y)
    n_classes = len(classes)
    Y.astype(int)
    num_bin = np.bincount(Y[:, 0])
    class_weights = {i: (num_samples / (n_classes * num_bin[i])) for i in range(6)}
    return class_weights


In [103]:
dummytrainY = to_categorical(trainY-1, 7)
habijabi = compute_weight(dummytrainY, np.unique(trainY))

TypeError: Cannot cast array data from dtype('float32') to dtype('int64') according to the rule 'safe'

In [112]:
trainYp= trainY.astype(int)
print(trainYp)
trainYp = np.expand_dims(trainYp, axis=1)
num_bin = np.bincount(trainYp[:, 0])

[6 6 6 ... 6 6 6]


In [114]:
print(num_bin)

[    0  3499 18824  3339  2462  7857 46862]


In [33]:
import numpy as np
A = np.array([3,4,6,10,24,89,45,43,46,99,100])
div3 = A[A%3!=0]
print("Elements of A not divisible by 3:")
print(div3)

Elements of A not divisible by 3:
[  4  10  89  43  46 100]


In [34]:
maska = A%3!=0

In [35]:
maska

array([False,  True, False,  True, False,  True, False,  True,  True,
       False,  True])