In [1]:
import pandas as pd
def patientSplitter(randomIDfile,df2,split_portion):
    import pandas as pd

    df1 = pd.read_csv(randomIDfile,header=None)
    split_portion_numer=int(split_portion*61)

    train_pat_list = [int(each) for each in df1.iloc[:split_portion_numer].values]
    test_pat_list = [int(each) for each in df1.iloc[split_portion_numer:].values]
    print(test_pat_list)
    df3 = []
    df4 = []
    for pat_ID in train_pat_list:
        df3.append(df2[df2.patID == pat_ID].values)
        print(pat_ID)
    for pat_ID in test_pat_list:
        df4.append(df2[df2.patID == pat_ID].values)
        print(pat_ID)
    del df2
    df3 = pd.np.vstack(df3)
    df4 = pd.np.vstack(df4)
    X_train = df3[:, :3000]
    X_test= df4[:, :3000]
    Y_train= df3[:,3000]
    Y_test= df4[:,3000]
    pat_train=df3[:, 3002:3003]
    pat_test= df4[:, 3002:3003]

    del pd
    return X_train,X_test,Y_train,Y_test,pat_train,pat_test

df2 = pd.read_csv("E:/SleepWell/ASSC/data/lastpurifiedallDataChannel1.csv", header=None)
df2.rename({3000: 'hyp', 3001: 'epoch', 3002: 'patID'}, axis="columns", inplace=True)

trainX, valX, trainY, valY, pat_train, pat_val = patientSplitter('randomizedIDs.csv', df2, 0.7)
print("Dataframe has been loaded")

[14, 30, 11, 15, 29, 8, 48, 24, 40, 54, 16, 37, 10, 39, 7, 18, 42, 57, 31]
35
21
22
43
9
56
34
58
26
6
3
55
33
2
27
13
46
45
38
47
17
5
25
32
1
52
50
12
41
51
4
19
0
23
53
49
36
20
44
60
59
28
14
30
11
15
29
8
48
24
40
54
16
37
10
39
7
18
42
57
31
Dataframe has been loaded


In [80]:
from sklearn.preprocessing import StandardScaler
data = trainX.flatten('A')
data = np.expand_dims(data, axis=1)
scaler = StandardScaler()
outdata= scaler.fit_transform(data)
toutdata = outdata.reshape(3000, int(outdata.shape[0]/3000))
#outdata = outdata.reshape(3000,:)

In [81]:
toutdata = outdata.reshape(int(outdata.shape[0]/3000),3000)

In [83]:
toutdata.shape

(82843, 3000)

In [78]:
adata = [[1, 3, 4], [6, 7, 8]]
adata=np.array(adata)
data = adata.flatten('A')
data = np.expand_dims(data, axis=1)
scaler = StandardScaler()
outdata= scaler.fit_transform(data)
outdata
data.reshape(2, 3)

C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[1, 3, 4],
       [6, 7, 8]])

In [3]:
import numpy as np
print(np.unique(pat_val))
print(np.unique(pat_train))

#np.savetxt("patAcc.csv", np.unique(pat_val), delimiter=",")

[ 7.  8. 10. 11. 14. 15. 16. 18. 24. 29. 30. 31. 37. 39. 40. 42. 48. 54.
 57.]
[ 1.  2.  3.  4.  5.  6.  9. 12. 13. 17. 19. 20. 21. 22. 23. 25. 26. 27.
 28. 32. 33. 34. 35. 36. 38. 41. 43. 44. 45. 46. 47. 49. 50. 51. 52. 53.
 55. 56. 58. 59. 60.]


In [49]:
trainX

array([[  -7.0032 ,   10.949  ,    0.45397, ...,    3.8603 ,  -32.781  ,
         -21.733  ],
       [ -37.844  ,  -63.254  ,  -81.022  , ...,  -54.14   ,  -39.778  ,
         -40.33   ],
       [ -52.575  ,  -60.032  ,  -37.568  , ...,   -9.673  , -105.7    ,
         -62.241  ],
       ...,
       [   8.0828 ,   -9.2701 ,   -0.77631, ...,    5.5255 ,   -3.2422 ,
           4.0642 ],
       [   4.0642 ,   -2.1463 ,    4.7949 , ...,   -2.6029 ,    1.3243 ,
           7.6261 ],
       [  -5.5255 ,   -3.7902 ,    0.50232, ...,   -0.22833,  -15.663  ,
         -11.919  ]])

In [15]:
import numpy as np
flatTrainX= trainX.flatten('A')

In [33]:
a = np.array([[1,2, 4, 5, 6], [3,4, 4]])
b= a.flatten
flatTrainX.shape
print(b)
trainX

<built-in method flatten of numpy.ndarray object at 0x0000017A235913A0>


array([[  -7.0032 ,   10.949  ,    0.45397, ...,    3.8603 ,  -32.781  ,
         -21.733  ],
       [ -37.844  ,  -63.254  ,  -81.022  , ...,  -54.14   ,  -39.778  ,
         -40.33   ],
       [ -52.575  ,  -60.032  ,  -37.568  , ...,   -9.673  , -105.7    ,
         -62.241  ],
       ...,
       [   8.0828 ,   -9.2701 ,   -0.77631, ...,    5.5255 ,   -3.2422 ,
           4.0642 ],
       [   4.0642 ,   -2.1463 ,    4.7949 , ...,   -2.6029 ,    1.3243 ,
           7.6261 ],
       [  -5.5255 ,   -3.7902 ,    0.50232, ...,   -0.22833,  -15.663  ,
         -11.919  ]])

In [66]:
import numpy as np
from sklearn.metrics import accuracy_score
patAcc=[]
valYp = np.expand_dims(valY, axis=1)
for pat in np.unique(pat_val).astype(int):
    mask = pat_val==pat
    patAcc.append(accuracy_score(valYp[mask], valYp[mask]))
    #print(acc)
print(patAcc)    
    

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [77]:
from keras.utils import to_categorical, plot_model
valYp = to_categorical(valY-1, 7)
valYp = np.argmax(valYp, axis=-1)
valYp = np.expand_dims(valYp, axis=1)

In [115]:
#predY = model.predict(self.valX, verbose=0)
            # predY = np.argmax(predY, axis=-1)
patAcc = []
for pat in np.unique(pat_val).astype(int):
    mask = pat_val == pat
    patAcc.append(accuracy_score(valYp[mask], valYp[mask]))
print(patAcc)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [116]:
print(pat_val.shape)
print(valY.shape)
print(valYp.shape)

(43144, 1)
(43144,)
(43144, 1)


In [102]:
def compute_weight(Y, classes):
    num_samples = len(Y)
    n_classes = len(classes)
    Y.astype(int)
    num_bin = np.bincount(Y[:, 0])
    class_weights = {i: (num_samples / (n_classes * num_bin[i])) for i in range(6)}
    return class_weights


In [103]:
dummytrainY = to_categorical(trainY-1, 7)
habijabi = compute_weight(dummytrainY, np.unique(trainY))

TypeError: Cannot cast array data from dtype('float32') to dtype('int64') according to the rule 'safe'

In [112]:
trainYp= trainY.astype(int)
print(trainYp)
trainYp = np.expand_dims(trainYp, axis=1)
num_bin = np.bincount(trainYp[:, 0])

[6 6 6 ... 6 6 6]


In [114]:
print(num_bin)

[    0  3499 18824  3339  2462  7857 46862]


In [33]:
import numpy as np
A = np.array([3,4,6,10,24,89,45,43,46,99,100])
div3 = A[A%3!=0]
print("Elements of A not divisible by 3:")
print(div3)

Elements of A not divisible by 3:
[  4  10  89  43  46 100]


In [34]:
maska = A%3!=0

In [35]:
maska

array([False,  True, False,  True, False,  True, False,  True,  True,
       False,  True])